- name: Deploy Container
  docker_container:
    name: "{{container_name}}"
    image: "{{container_image}}"
    pull: true
    restart_policy: always
    state: started
    ports: "{{container_ports}}"
